### ISSUE TITLE
New thinking on Container Components

### ISSUE THREAD

**Issue by julianjohannesen** [learn-co-curriculum/react-container-components#10]
This is the note from Dan Abramov's Medium article on presentational versus container components: 

"Update from 2019: I wrote this article a long time ago and my views have since evolved. In particular, I don’t suggest splitting your components like this anymore. If you find it natural in your codebase, this pattern can be handy. But I’ve seen it enforced without any necessity and with almost dogmatic fervor far too many times. The main reason I found it useful was because it let me separate complex stateful logic from other aspects of the component. Hooks let me do the same thing without an arbitrary division. This text is left intact for historical reasons but don’t take it too seriously."

**Comment by maxwellbenton** [comment]
Hi @julianjohannesen,

Thank you for providing this feedback. We've updated this lesson to include a callout to this note. While container components are no longer emphasized, they do provide a good app structure for students new to React, especially as the container/presentation design has some features that may be familiar from object-orientation taught in previous sections of our courses. 

We intend to include materials on hooks in an upcoming update to our React materials, and will update this lesson further at that time, but will likely continue to include this content to preface it and help students get comfortable with building multi-component applications.

Thank you for contributing!
