### ISSUE TITLE
"What is" proptypes?

### ISSUE THREAD

**Issue by tuzmusic** [learn-co-curriculum/react-container-components#11]
This lesson talks about PropTypes, referring to it as if it's something we know how to use already. So I looked it up. It does seem useful, but I do see that after React 15.5 it's no longer native with React, and requires the `prop-types` package. Perhaps this lesson (or another) could explain prop-types and its usage.

**Comment by gac2117** [comment]
I agree! also where in `BookList` are we supposed to add this:
```
BookList.propTypes = {
  books: PropTypes.shape({
    img_url: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired
  });
}
```

Because the `BookList` code looks like this:

```
const BookList = ({ books }) => (
  <div className="book-list">
    { books.map(book => <Book title={book.title} img_url={book.image_url} />) }
  </div>
)
```

Being more specific about placement would help greatly. 
And yes, explaining `PropTypes` before suddenly using it would also be helpful...

**Comment by maxwellbenton** [comment]
Hi @tuzmusic,

Thank you for this feedback. We've updated this lesson and removed the reference to propTypes as it is not covered in our content, which should resolve this issue.

We apologize for any confusion this may have caused, but thank you for contributing and helping to improve this lesson!
