### ISSUE TITLE
Separating Concerns using a Container Component example needs to be clarified

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/react-container-components#12]
The example code snippet should be divided into three code snippets with the proper filenames to avoid confusion.  So like:

```
// in Book.js

const Book = ({ title, img_url }) => (
  <div className="book">
    <img src={ img_url } />
    <h3>{ title }</h3>
  </div>
)
```
 

```
// in BookList.js 

const BookList = ({ books }) => (
  <div className="book-list">
    { books.map(book => <Book title={book.title} img_url={book.image_url} />) }
  </div>
)
```
 

```
// in BookListContainer.js

class BookListContainer extends React.Component {
  constructor() {
    super()
 
    this.state = {
      books: []
    };
  }
 
  componentDidMount() {
    fetch('/api/current_user/book_list')
      .then(response => response.json())
      .then(books => this.setState({ books }))
  }
 
  render() {
    return <BookList books={this.state.books} />
  }
}
```

But it is still confusing because the Readme says : "That component, which is stateless, is now incredibly stable as well as concise, especially because we've pulled the rendering logic out and placed it in a discrete function Book."
So is `Book` a function inside an existing component? Or is it a functional component? Can it be reworded so it's more clear?

And it may be redundant, but adding the `import React from 'react'` and even `import BookList from './components/BookList'` on each code snippet would help distinguish the parent and child components for newbie learners like me.

**Comment by maxwellbenton** [comment]
Hi @gac2117,

Thank you for this feedback. We've updated this lesson using your suggestions - the final code snippet has been separated out into snippets for each file, with all the required code added (while this lesson isn't set up as a code along, the code will work in a React app now). We've also updated the instructions around this section, which should help clarify this lesson for future students.

We apologize for any confusion this may have caused, but thank you for contributing and helping to improve this lesson!
