### ISSUE TITLE
componentDidMount() is a function that has not yet been introduced per the curriculum

### ISSUE THREAD

**Issue by keepitmovingforward** [learn-co-curriculum/react-container-components#13]
This lab utilizes the method "componentDidMount()" prior to it being introduced. I thought it was an error in the code since there was no call to this method before

render() {
    return <BookList books={this.state.books} />
  }

My coach explained that the "componentDidMount()" works in a way similar to "DOMContentLoaded" in vanilla JS but otherwise, that added method was confusing.

**Comment by maxwellbenton** [comment]
Hi @icydwei,

Thank you for opening this issue and providing feedback. I've double-checked the order of lessons for your cohort - `componentDidMount()` is introduced in the Lifecycle Methods section ([starting with mounting](https://github.com/learn-co-curriculum/react-component-lifecycle-overview)) and is also used in the Async React section just prior to where this lesson is located in the curriculum. 

It may be possible this content was deployed out of order to your cohort. However, it looks like the topic of `componentDidMount` has been introduced based on the order of lessons in the curriculum. I am going to close this issue for now, but please feel free to reopen it if you feel this is issue is not resolved or if there is something I am missing.

Thank you!
