### ISSUE TITLE
Typo in BookList component

### ISSUE THREAD

**Issue by breadoliveoilsalt** [learn-co-curriculum/react-container-components#8]
Just a small thing -- under "SEPARATING CONCERNS USING A CONTAINER COMPONENT", please see the code for BookList component, lines 10 and 14.  Shouldn't the parentheses after the => be replaced with curly brackets {}?  Thanks!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
