### ISSUE TITLE
Bug in example: quoted text should be in curly braces

### ISSUE THREAD

**Issue by acohn8** [learn-co-curriculum/react-container-components#9]
The code below will not work as expected; "book.title" and "book.image_url"  will display literally instead as variables since they are enclosed in quotes instead of JSX curly braces:

```
const BookList = ({ books }) => (
  <div className="book-list">
    {books.map(book => <Book title="book.title" img_url="book.image_url" />)}
  </div>
);
```

This should fix the problem:

```
const BookList = ({ books }) => (
  <div className="book-list">
    {books.map(book => <Book title={book.title} img_url={book.image_url} />)}
  </div>
);
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
